FROM ubuntu:latest

WORKDIR /usr/service

RUN apt-get update -y && apt install wget -y && apt install xz-utils -y

RUN wget https://nodejs.org/download/release/v17.9.1/node-v17.9.1-linux-x64.tar.xz \
&& tar -xvf node-v17.9.1-linux-x64.tar.xz

RUN cp -r node-v17.9.1-linux-x64 /usr/

RUN apt-get update -y && apt-get install -y npm && apt-get install -y gnupg2

RUN npm install --global yarn

COPY . /usr/service

RUN npm install

# default env variables in case none were send in commandline(--build-arg ARG) or docker-compose.
ENV REACT_APP_ENVIRONMENT development
ENV REACT_APP_API_GATEWAY_URI localhost:8585
ENV SKIP_PREFLIGHT_CHECK true
ENV PATH="/usr/node-v17.9.1-linux-x64/bin:$PATH"
ENV NODE_PATH src/
ENV PORT 5000

EXPOSE $PORT

CMD yarn start
